#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]

/* automatically generated by rust-bindgen 0.72.1 */

pub const _VCRT_COMPILER_PREPROCESSOR: u32 = 1;
pub const _SAL_VERSION: u32 = 20;
pub const __SAL_H_VERSION: u32 = 180000000;
pub const _USE_DECLSPECS_FOR_SAL: u32 = 0;
pub const _USE_ATTRIBUTES_FOR_SAL: u32 = 0;
pub const _CRT_PACKING: u32 = 8;
pub const _HAS_EXCEPTIONS: u32 = 1;
pub const _STL_LANG: u32 = 0;
pub const _HAS_CXX17: u32 = 0;
pub const _HAS_CXX20: u32 = 0;
pub const _HAS_CXX23: u32 = 0;
pub const _HAS_CXX26: u32 = 0;
pub const _HAS_NODISCARD: u32 = 0;
pub const WCHAR_MIN: u32 = 0;
pub const WCHAR_MAX: u32 = 65535;
pub const WINT_MIN: u32 = 0;
pub const WINT_MAX: u32 = 65535;
pub const ZCAN_USBCANFD_200U: u32 = 41;
pub const VCI_USBCAN_E_U: u32 = 20;
pub const VCI_USBCAN_2E_U: u32 = 21;
pub const STATUS_ERR: u32 = 0;
pub const STATUS_OK: u32 = 1;
pub const STATUS_ONLINE: u32 = 2;
pub const STATUS_OFFLINE: u32 = 3;
pub const STATUS_UNSUPPORTED: u32 = 4;
pub const INVALID_CHANNEL_HANDLE: u32 = 0;
pub const INVALID_DEVICE_HANDLE: u32 = 0;
pub const CAN_EFF_FLAG: u32 = 2147483648;
pub const CAN_RTR_FLAG: u32 = 1073741824;
pub const CAN_ERR_FLAG: u32 = 536870912;
pub const CAN_ID_FLAG: u32 = 536870911;
pub const CAN_SFF_MASK: u32 = 2047;
pub const CAN_EFF_MASK: u32 = 536870911;
pub const CAN_ERR_MASK: u32 = 536870911;
pub const CAN_MAX_DLEN: u32 = 8;
pub const CANFD_MAX_DLEN: u32 = 64;
pub const TYPE_CAN: u32 = 0;
pub const TYPE_CANFD: u32 = 1;
pub type va_list = *mut ::std::os::raw::c_char;
unsafe extern "C" {
    pub fn __va_start(arg1: *mut *mut ::std::os::raw::c_char, ...);
}
pub type __vcrt_bool = bool;
pub type wchar_t = ::std::os::raw::c_ushort;
unsafe extern "C" {
    pub fn __security_init_cookie();
}
unsafe extern "C" {
    pub fn __security_check_cookie(_StackCookie: usize);
}
unsafe extern "C" {
    pub fn __report_gsfailure(_StackCookie: usize) -> !;
}
unsafe extern "C" {
    pub static mut __security_cookie: usize;
}
pub type int_least8_t = ::std::os::raw::c_schar;
pub type int_least16_t = ::std::os::raw::c_short;
pub type int_least32_t = ::std::os::raw::c_int;
pub type int_least64_t = ::std::os::raw::c_longlong;
pub type uint_least8_t = ::std::os::raw::c_uchar;
pub type uint_least16_t = ::std::os::raw::c_ushort;
pub type uint_least32_t = ::std::os::raw::c_uint;
pub type uint_least64_t = ::std::os::raw::c_ulonglong;
pub type int_fast8_t = ::std::os::raw::c_schar;
pub type int_fast16_t = ::std::os::raw::c_int;
pub type int_fast32_t = ::std::os::raw::c_int;
pub type int_fast64_t = ::std::os::raw::c_longlong;
pub type uint_fast8_t = ::std::os::raw::c_uchar;
pub type uint_fast16_t = ::std::os::raw::c_uint;
pub type uint_fast32_t = ::std::os::raw::c_uint;
pub type uint_fast64_t = ::std::os::raw::c_ulonglong;
pub type intmax_t = ::std::os::raw::c_longlong;
pub type uintmax_t = ::std::os::raw::c_ulonglong;
pub type UINT = ::std::os::raw::c_uint;
pub type BYTE = ::std::os::raw::c_uchar;
pub type USHORT = ::std::os::raw::c_ushort;
pub type UCHAR = ::std::os::raw::c_uchar;
pub type DWORD = ::std::os::raw::c_ulong;
pub type ULONG = ::std::os::raw::c_ulong;
pub type PVOID = *mut ::std::os::raw::c_void;
pub type INT = ::std::os::raw::c_int;
pub type CHAR = ::std::os::raw::c_char;
pub type UINT64 = u64;
#[doc = "  \\struct Meta\nNode mata information."]
pub type Meta = _Meta;
#[doc = "  \\struct Pair\nThe KeyValue of the attribute."]
pub type Pair = _Pair;
#[doc = "  \\struct Options\nOptional options for node mata."]
pub type Options = _Options;
#[doc = "  \\struct ConfigNode\n  ConfigNode"]
pub type ConfigNode = _ConfigNode;
#[doc = "  \\struct Options\nOptional options for node mata."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _Options {
    #[doc = " Optional data types"]
    pub type_: *const ::std::os::raw::c_char,
    #[doc = " Optional values"]
    pub value: *const ::std::os::raw::c_char,
    #[doc = " Optional description information"]
    pub desc: *const ::std::os::raw::c_char,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _Options"][::std::mem::size_of::<_Options>() - 24usize];
    ["Alignment of _Options"][::std::mem::align_of::<_Options>() - 8usize];
    ["Offset of field: _Options::type_"][::std::mem::offset_of!(_Options, type_) - 0usize];
    ["Offset of field: _Options::value"][::std::mem::offset_of!(_Options, value) - 8usize];
    ["Offset of field: _Options::desc"][::std::mem::offset_of!(_Options, desc) - 16usize];
};
#[doc = "  \\struct Meta\nNode mata information."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _Meta {
    pub type_: *const ::std::os::raw::c_char,
    pub desc: *const ::std::os::raw::c_char,
    pub read_only: ::std::os::raw::c_int,
    #[doc = " Tips for input format of configuration items"]
    pub format: *const ::std::os::raw::c_char,
    pub min_value: f64,
    pub max_value: f64,
    pub unit: *const ::std::os::raw::c_char,
    pub delta: f64,
    pub visible: *const ::std::os::raw::c_char,
    pub enable: *const ::std::os::raw::c_char,
    pub editable: ::std::os::raw::c_int,
    pub options: *mut *mut Options,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _Meta"][::std::mem::size_of::<_Meta>() - 96usize];
    ["Alignment of _Meta"][::std::mem::align_of::<_Meta>() - 8usize];
    ["Offset of field: _Meta::type_"][::std::mem::offset_of!(_Meta, type_) - 0usize];
    ["Offset of field: _Meta::desc"][::std::mem::offset_of!(_Meta, desc) - 8usize];
    ["Offset of field: _Meta::read_only"][::std::mem::offset_of!(_Meta, read_only) - 16usize];
    ["Offset of field: _Meta::format"][::std::mem::offset_of!(_Meta, format) - 24usize];
    ["Offset of field: _Meta::min_value"][::std::mem::offset_of!(_Meta, min_value) - 32usize];
    ["Offset of field: _Meta::max_value"][::std::mem::offset_of!(_Meta, max_value) - 40usize];
    ["Offset of field: _Meta::unit"][::std::mem::offset_of!(_Meta, unit) - 48usize];
    ["Offset of field: _Meta::delta"][::std::mem::offset_of!(_Meta, delta) - 56usize];
    ["Offset of field: _Meta::visible"][::std::mem::offset_of!(_Meta, visible) - 64usize];
    ["Offset of field: _Meta::enable"][::std::mem::offset_of!(_Meta, enable) - 72usize];
    ["Offset of field: _Meta::editable"][::std::mem::offset_of!(_Meta, editable) - 80usize];
    ["Offset of field: _Meta::options"][::std::mem::offset_of!(_Meta, options) - 88usize];
};
#[doc = "  \\struct Pair\nThe KeyValue of the attribute."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _Pair {
    pub key: *const ::std::os::raw::c_char,
    pub value: *const ::std::os::raw::c_char,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _Pair"][::std::mem::size_of::<_Pair>() - 16usize];
    ["Alignment of _Pair"][::std::mem::align_of::<_Pair>() - 8usize];
    ["Offset of field: _Pair::key"][::std::mem::offset_of!(_Pair, key) - 0usize];
    ["Offset of field: _Pair::value"][::std::mem::offset_of!(_Pair, value) - 8usize];
};
#[doc = "  \\struct ConfigNode\n  ConfigNode"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _ConfigNode {
    pub name: *const ::std::os::raw::c_char,
    pub value: *const ::std::os::raw::c_char,
    pub binding_value: *const ::std::os::raw::c_char,
    pub path: *const ::std::os::raw::c_char,
    #[doc = " Configuration item information"]
    pub meta_info: *mut Meta,
    pub children: *mut *mut ConfigNode,
    pub attributes: *mut *mut Pair,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _ConfigNode"][::std::mem::size_of::<_ConfigNode>() - 56usize];
    ["Alignment of _ConfigNode"][::std::mem::align_of::<_ConfigNode>() - 8usize];
    ["Offset of field: _ConfigNode::name"][::std::mem::offset_of!(_ConfigNode, name) - 0usize];
    ["Offset of field: _ConfigNode::value"][::std::mem::offset_of!(_ConfigNode, value) - 8usize];
    ["Offset of field: _ConfigNode::binding_value"]
        [::std::mem::offset_of!(_ConfigNode, binding_value) - 16usize];
    ["Offset of field: _ConfigNode::path"][::std::mem::offset_of!(_ConfigNode, path) - 24usize];
    ["Offset of field: _ConfigNode::meta_info"]
        [::std::mem::offset_of!(_ConfigNode, meta_info) - 32usize];
    ["Offset of field: _ConfigNode::children"]
        [::std::mem::offset_of!(_ConfigNode, children) - 40usize];
    ["Offset of field: _ConfigNode::attributes"]
        [::std::mem::offset_of!(_ConfigNode, attributes) - 48usize];
};
#[doc = "Retrieve the description information of the attribute.\n\n \\retval ConfigNode"]
pub type GetPropertysFunc = ::std::option::Option<unsafe extern "C" fn() -> *const ConfigNode>;
#[doc = "Set the value of the attribute of the specified path.\n\\ parameter [in] path: The path of the attribute.\n\\ param [in] value: The value of the attribute.\n\nRetval returns 1 for success and 0 for failure."]
pub type SetValueFunc = ::std::option::Option<
    unsafe extern "C" fn(
        path: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int,
>;
#[doc = "Retrieve the value of the attribute of the specified path.\n\\ parameter [in] path: The path of the attribute.\nRetval successfully returns the value of the property, while failure returns NULL."]
pub type GetValueFunc = ::std::option::Option<
    unsafe extern "C" fn(path: *const ::std::os::raw::c_char) -> *const ::std::os::raw::c_char,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct tagIProperty {
    pub SetValue: SetValueFunc,
    pub GetValue: GetValueFunc,
    pub GetPropertys: GetPropertysFunc,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of tagIProperty"][::std::mem::size_of::<tagIProperty>() - 24usize];
    ["Alignment of tagIProperty"][::std::mem::align_of::<tagIProperty>() - 8usize];
    ["Offset of field: tagIProperty::SetValue"]
        [::std::mem::offset_of!(tagIProperty, SetValue) - 0usize];
    ["Offset of field: tagIProperty::GetValue"]
        [::std::mem::offset_of!(tagIProperty, GetValue) - 8usize];
    ["Offset of field: tagIProperty::GetPropertys"]
        [::std::mem::offset_of!(tagIProperty, GetPropertys) - 16usize];
};
pub type IProperty = tagIProperty;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct can_frame {
    pub can_id: UINT,
    pub can_dlc: BYTE,
    pub __pad: BYTE,
    pub __res0: BYTE,
    pub __res1: BYTE,
    pub data: [BYTE; 8usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of can_frame"][::std::mem::size_of::<can_frame>() - 16usize];
    ["Alignment of can_frame"][::std::mem::align_of::<can_frame>() - 4usize];
    ["Offset of field: can_frame::can_id"][::std::mem::offset_of!(can_frame, can_id) - 0usize];
    ["Offset of field: can_frame::can_dlc"][::std::mem::offset_of!(can_frame, can_dlc) - 4usize];
    ["Offset of field: can_frame::__pad"][::std::mem::offset_of!(can_frame, __pad) - 5usize];
    ["Offset of field: can_frame::__res0"][::std::mem::offset_of!(can_frame, __res0) - 6usize];
    ["Offset of field: can_frame::__res1"][::std::mem::offset_of!(can_frame, __res1) - 7usize];
    ["Offset of field: can_frame::data"][::std::mem::offset_of!(can_frame, data) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct canfd_frame {
    pub can_id: UINT,
    pub len: BYTE,
    pub flags: BYTE,
    pub __res0: BYTE,
    pub __res1: BYTE,
    pub data: [BYTE; 64usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of canfd_frame"][::std::mem::size_of::<canfd_frame>() - 72usize];
    ["Alignment of canfd_frame"][::std::mem::align_of::<canfd_frame>() - 4usize];
    ["Offset of field: canfd_frame::can_id"][::std::mem::offset_of!(canfd_frame, can_id) - 0usize];
    ["Offset of field: canfd_frame::len"][::std::mem::offset_of!(canfd_frame, len) - 4usize];
    ["Offset of field: canfd_frame::flags"][::std::mem::offset_of!(canfd_frame, flags) - 5usize];
    ["Offset of field: canfd_frame::__res0"][::std::mem::offset_of!(canfd_frame, __res0) - 6usize];
    ["Offset of field: canfd_frame::__res1"][::std::mem::offset_of!(canfd_frame, __res1) - 7usize];
    ["Offset of field: canfd_frame::data"][::std::mem::offset_of!(canfd_frame, data) - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct tagZCAN_DEVICE_INFO {
    pub hw_Version: USHORT,
    pub fw_Version: USHORT,
    pub dr_Version: USHORT,
    pub in_Version: USHORT,
    pub irq_Num: USHORT,
    pub can_Num: BYTE,
    pub str_Serial_Num: [UCHAR; 20usize],
    pub str_hw_Type: [UCHAR; 40usize],
    pub reserved: [USHORT; 4usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of tagZCAN_DEVICE_INFO"][::std::mem::size_of::<tagZCAN_DEVICE_INFO>() - 80usize];
    ["Alignment of tagZCAN_DEVICE_INFO"][::std::mem::align_of::<tagZCAN_DEVICE_INFO>() - 2usize];
    ["Offset of field: tagZCAN_DEVICE_INFO::hw_Version"]
        [::std::mem::offset_of!(tagZCAN_DEVICE_INFO, hw_Version) - 0usize];
    ["Offset of field: tagZCAN_DEVICE_INFO::fw_Version"]
        [::std::mem::offset_of!(tagZCAN_DEVICE_INFO, fw_Version) - 2usize];
    ["Offset of field: tagZCAN_DEVICE_INFO::dr_Version"]
        [::std::mem::offset_of!(tagZCAN_DEVICE_INFO, dr_Version) - 4usize];
    ["Offset of field: tagZCAN_DEVICE_INFO::in_Version"]
        [::std::mem::offset_of!(tagZCAN_DEVICE_INFO, in_Version) - 6usize];
    ["Offset of field: tagZCAN_DEVICE_INFO::irq_Num"]
        [::std::mem::offset_of!(tagZCAN_DEVICE_INFO, irq_Num) - 8usize];
    ["Offset of field: tagZCAN_DEVICE_INFO::can_Num"]
        [::std::mem::offset_of!(tagZCAN_DEVICE_INFO, can_Num) - 10usize];
    ["Offset of field: tagZCAN_DEVICE_INFO::str_Serial_Num"]
        [::std::mem::offset_of!(tagZCAN_DEVICE_INFO, str_Serial_Num) - 11usize];
    ["Offset of field: tagZCAN_DEVICE_INFO::str_hw_Type"]
        [::std::mem::offset_of!(tagZCAN_DEVICE_INFO, str_hw_Type) - 31usize];
    ["Offset of field: tagZCAN_DEVICE_INFO::reserved"]
        [::std::mem::offset_of!(tagZCAN_DEVICE_INFO, reserved) - 72usize];
};
pub type ZCAN_DEVICE_INFO = tagZCAN_DEVICE_INFO;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct tagZCAN_CHANNEL_INIT_CONFIG {
    pub can_type: UINT,
    pub __bindgen_anon_1: tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1 {
    pub can: tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1__bindgen_ty_1,
    pub canfd: tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1__bindgen_ty_2,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1__bindgen_ty_1 {
    pub acc_code: UINT,
    pub acc_mask: UINT,
    pub reserved: UINT,
    pub filter: BYTE,
    pub timing0: BYTE,
    pub timing1: BYTE,
    pub mode: BYTE,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1__bindgen_ty_1"][::std::mem::size_of::<
        tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1__bindgen_ty_1,
    >() - 16usize];
    ["Alignment of tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1__bindgen_ty_1"][::std::mem::align_of::<
        tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1__bindgen_ty_1,
    >() - 4usize];
    ["Offset of field: tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1__bindgen_ty_1::acc_code"][::std::mem::offset_of!(
        tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1__bindgen_ty_1,
        acc_code
    )
        - 0usize];
    ["Offset of field: tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1__bindgen_ty_1::acc_mask"][::std::mem::offset_of!(
        tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1__bindgen_ty_1,
        acc_mask
    )
        - 4usize];
    ["Offset of field: tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1__bindgen_ty_1::reserved"][::std::mem::offset_of!(
        tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1__bindgen_ty_1,
        reserved
    )
        - 8usize];
    ["Offset of field: tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1__bindgen_ty_1::filter"][::std::mem::offset_of!(
        tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1__bindgen_ty_1,
        filter
    )
        - 12usize];
    ["Offset of field: tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1__bindgen_ty_1::timing0"][::std::mem::offset_of!(
        tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1__bindgen_ty_1,
        timing0
    )
        - 13usize];
    ["Offset of field: tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1__bindgen_ty_1::timing1"][::std::mem::offset_of!(
        tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1__bindgen_ty_1,
        timing1
    )
        - 14usize];
    ["Offset of field: tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1__bindgen_ty_1::mode"][::std::mem::offset_of!(
        tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1__bindgen_ty_1,
        mode
    ) - 15usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1__bindgen_ty_2 {
    pub acc_code: UINT,
    pub acc_mask: UINT,
    pub abit_timing: UINT,
    pub dbit_timing: UINT,
    pub brp: UINT,
    pub filter: BYTE,
    pub mode: BYTE,
    pub pad: USHORT,
    pub reserved: UINT,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1__bindgen_ty_2"][::std::mem::size_of::<
        tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1__bindgen_ty_2,
    >() - 28usize];
    ["Alignment of tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1__bindgen_ty_2"][::std::mem::align_of::<
        tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1__bindgen_ty_2,
    >() - 4usize];
    ["Offset of field: tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1__bindgen_ty_2::acc_code"][::std::mem::offset_of!(
        tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1__bindgen_ty_2,
        acc_code
    )
        - 0usize];
    ["Offset of field: tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1__bindgen_ty_2::acc_mask"][::std::mem::offset_of!(
        tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1__bindgen_ty_2,
        acc_mask
    )
        - 4usize];
    ["Offset of field: tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1__bindgen_ty_2::abit_timing"][::std::mem::offset_of!(
        tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1__bindgen_ty_2,
        abit_timing
    )
        - 8usize];
    ["Offset of field: tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1__bindgen_ty_2::dbit_timing"][::std::mem::offset_of!(
        tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1__bindgen_ty_2,
        dbit_timing
    )
        - 12usize];
    ["Offset of field: tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1__bindgen_ty_2::brp"][::std::mem::offset_of!(
        tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1__bindgen_ty_2,
        brp
    ) - 16usize];
    ["Offset of field: tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1__bindgen_ty_2::filter"][::std::mem::offset_of!(
        tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1__bindgen_ty_2,
        filter
    )
        - 20usize];
    ["Offset of field: tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1__bindgen_ty_2::mode"][::std::mem::offset_of!(
        tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1__bindgen_ty_2,
        mode
    ) - 21usize];
    ["Offset of field: tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1__bindgen_ty_2::pad"][::std::mem::offset_of!(
        tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1__bindgen_ty_2,
        pad
    ) - 22usize];
    ["Offset of field: tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1__bindgen_ty_2::reserved"][::std::mem::offset_of!(
        tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1__bindgen_ty_2,
        reserved
    )
        - 24usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1"]
        [::std::mem::size_of::<tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1>() - 28usize];
    ["Alignment of tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1"]
        [::std::mem::align_of::<tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1>() - 4usize];
    ["Offset of field: tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1::can"]
        [::std::mem::offset_of!(tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1, can) - 0usize];
    ["Offset of field: tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1::canfd"]
        [::std::mem::offset_of!(tagZCAN_CHANNEL_INIT_CONFIG__bindgen_ty_1, canfd) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of tagZCAN_CHANNEL_INIT_CONFIG"]
        [::std::mem::size_of::<tagZCAN_CHANNEL_INIT_CONFIG>() - 32usize];
    ["Alignment of tagZCAN_CHANNEL_INIT_CONFIG"]
        [::std::mem::align_of::<tagZCAN_CHANNEL_INIT_CONFIG>() - 4usize];
    ["Offset of field: tagZCAN_CHANNEL_INIT_CONFIG::can_type"]
        [::std::mem::offset_of!(tagZCAN_CHANNEL_INIT_CONFIG, can_type) - 0usize];
};
pub type ZCAN_CHANNEL_INIT_CONFIG = tagZCAN_CHANNEL_INIT_CONFIG;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct tagZCAN_Transmit_Data {
    pub frame: can_frame,
    pub transmit_type: UINT,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of tagZCAN_Transmit_Data"][::std::mem::size_of::<tagZCAN_Transmit_Data>() - 20usize];
    ["Alignment of tagZCAN_Transmit_Data"]
        [::std::mem::align_of::<tagZCAN_Transmit_Data>() - 4usize];
    ["Offset of field: tagZCAN_Transmit_Data::frame"]
        [::std::mem::offset_of!(tagZCAN_Transmit_Data, frame) - 0usize];
    ["Offset of field: tagZCAN_Transmit_Data::transmit_type"]
        [::std::mem::offset_of!(tagZCAN_Transmit_Data, transmit_type) - 16usize];
};
pub type ZCAN_Transmit_Data = tagZCAN_Transmit_Data;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct tagZCAN_Receive_Data {
    pub frame: can_frame,
    pub timestamp: UINT64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of tagZCAN_Receive_Data"][::std::mem::size_of::<tagZCAN_Receive_Data>() - 24usize];
    ["Alignment of tagZCAN_Receive_Data"][::std::mem::align_of::<tagZCAN_Receive_Data>() - 8usize];
    ["Offset of field: tagZCAN_Receive_Data::frame"]
        [::std::mem::offset_of!(tagZCAN_Receive_Data, frame) - 0usize];
    ["Offset of field: tagZCAN_Receive_Data::timestamp"]
        [::std::mem::offset_of!(tagZCAN_Receive_Data, timestamp) - 16usize];
};
pub type ZCAN_Receive_Data = tagZCAN_Receive_Data;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct tagZCAN_TransmitFD_Data {
    pub frame: canfd_frame,
    pub transmit_type: UINT,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of tagZCAN_TransmitFD_Data"][::std::mem::size_of::<tagZCAN_TransmitFD_Data>() - 76usize];
    ["Alignment of tagZCAN_TransmitFD_Data"]
        [::std::mem::align_of::<tagZCAN_TransmitFD_Data>() - 4usize];
    ["Offset of field: tagZCAN_TransmitFD_Data::frame"]
        [::std::mem::offset_of!(tagZCAN_TransmitFD_Data, frame) - 0usize];
    ["Offset of field: tagZCAN_TransmitFD_Data::transmit_type"]
        [::std::mem::offset_of!(tagZCAN_TransmitFD_Data, transmit_type) - 72usize];
};
pub type ZCAN_TransmitFD_Data = tagZCAN_TransmitFD_Data;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct tagZCAN_ReceiveFD_Data {
    pub frame: canfd_frame,
    pub timestamp: UINT64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of tagZCAN_ReceiveFD_Data"][::std::mem::size_of::<tagZCAN_ReceiveFD_Data>() - 80usize];
    ["Alignment of tagZCAN_ReceiveFD_Data"]
        [::std::mem::align_of::<tagZCAN_ReceiveFD_Data>() - 8usize];
    ["Offset of field: tagZCAN_ReceiveFD_Data::frame"]
        [::std::mem::offset_of!(tagZCAN_ReceiveFD_Data, frame) - 0usize];
    ["Offset of field: tagZCAN_ReceiveFD_Data::timestamp"]
        [::std::mem::offset_of!(tagZCAN_ReceiveFD_Data, timestamp) - 72usize];
};
pub type ZCAN_ReceiveFD_Data = tagZCAN_ReceiveFD_Data;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _VCI_BOARD_INFO {
    pub hw_Version: USHORT,
    pub fw_Version: USHORT,
    pub dr_Version: USHORT,
    pub in_Version: USHORT,
    pub irq_Num: USHORT,
    pub can_Num: BYTE,
    pub str_Serial_Num: [CHAR; 20usize],
    pub str_hw_Type: [CHAR; 40usize],
    pub Reserved: [USHORT; 4usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _VCI_BOARD_INFO"][::std::mem::size_of::<_VCI_BOARD_INFO>() - 80usize];
    ["Alignment of _VCI_BOARD_INFO"][::std::mem::align_of::<_VCI_BOARD_INFO>() - 2usize];
    ["Offset of field: _VCI_BOARD_INFO::hw_Version"]
        [::std::mem::offset_of!(_VCI_BOARD_INFO, hw_Version) - 0usize];
    ["Offset of field: _VCI_BOARD_INFO::fw_Version"]
        [::std::mem::offset_of!(_VCI_BOARD_INFO, fw_Version) - 2usize];
    ["Offset of field: _VCI_BOARD_INFO::dr_Version"]
        [::std::mem::offset_of!(_VCI_BOARD_INFO, dr_Version) - 4usize];
    ["Offset of field: _VCI_BOARD_INFO::in_Version"]
        [::std::mem::offset_of!(_VCI_BOARD_INFO, in_Version) - 6usize];
    ["Offset of field: _VCI_BOARD_INFO::irq_Num"]
        [::std::mem::offset_of!(_VCI_BOARD_INFO, irq_Num) - 8usize];
    ["Offset of field: _VCI_BOARD_INFO::can_Num"]
        [::std::mem::offset_of!(_VCI_BOARD_INFO, can_Num) - 10usize];
    ["Offset of field: _VCI_BOARD_INFO::str_Serial_Num"]
        [::std::mem::offset_of!(_VCI_BOARD_INFO, str_Serial_Num) - 11usize];
    ["Offset of field: _VCI_BOARD_INFO::str_hw_Type"]
        [::std::mem::offset_of!(_VCI_BOARD_INFO, str_hw_Type) - 31usize];
    ["Offset of field: _VCI_BOARD_INFO::Reserved"]
        [::std::mem::offset_of!(_VCI_BOARD_INFO, Reserved) - 72usize];
};
pub type VCI_BOARD_INFO = _VCI_BOARD_INFO;
pub type PVCI_BOARD_INFO = *mut _VCI_BOARD_INFO;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _VCI_CAN_OBJ {
    pub ID: UINT,
    pub TimeStamp: UINT,
    pub TimeFlag: BYTE,
    pub SendType: BYTE,
    pub RemoteFlag: BYTE,
    pub ExternFlag: BYTE,
    pub DataLen: BYTE,
    pub Data: [BYTE; 8usize],
    pub Reserved: [BYTE; 3usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _VCI_CAN_OBJ"][::std::mem::size_of::<_VCI_CAN_OBJ>() - 24usize];
    ["Alignment of _VCI_CAN_OBJ"][::std::mem::align_of::<_VCI_CAN_OBJ>() - 4usize];
    ["Offset of field: _VCI_CAN_OBJ::ID"][::std::mem::offset_of!(_VCI_CAN_OBJ, ID) - 0usize];
    ["Offset of field: _VCI_CAN_OBJ::TimeStamp"]
        [::std::mem::offset_of!(_VCI_CAN_OBJ, TimeStamp) - 4usize];
    ["Offset of field: _VCI_CAN_OBJ::TimeFlag"]
        [::std::mem::offset_of!(_VCI_CAN_OBJ, TimeFlag) - 8usize];
    ["Offset of field: _VCI_CAN_OBJ::SendType"]
        [::std::mem::offset_of!(_VCI_CAN_OBJ, SendType) - 9usize];
    ["Offset of field: _VCI_CAN_OBJ::RemoteFlag"]
        [::std::mem::offset_of!(_VCI_CAN_OBJ, RemoteFlag) - 10usize];
    ["Offset of field: _VCI_CAN_OBJ::ExternFlag"]
        [::std::mem::offset_of!(_VCI_CAN_OBJ, ExternFlag) - 11usize];
    ["Offset of field: _VCI_CAN_OBJ::DataLen"]
        [::std::mem::offset_of!(_VCI_CAN_OBJ, DataLen) - 12usize];
    ["Offset of field: _VCI_CAN_OBJ::Data"][::std::mem::offset_of!(_VCI_CAN_OBJ, Data) - 13usize];
    ["Offset of field: _VCI_CAN_OBJ::Reserved"]
        [::std::mem::offset_of!(_VCI_CAN_OBJ, Reserved) - 21usize];
};
pub type VCI_CAN_OBJ = _VCI_CAN_OBJ;
pub type PVCI_CAN_OBJ = *mut _VCI_CAN_OBJ;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _VCI_CAN_STATUS {
    pub ErrInterrupt: UCHAR,
    pub regMode: UCHAR,
    pub regStatus: UCHAR,
    pub regALCapture: UCHAR,
    pub regECCapture: UCHAR,
    pub regEWLimit: UCHAR,
    pub regRECounter: UCHAR,
    pub regTECounter: UCHAR,
    pub Reserved: DWORD,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _VCI_CAN_STATUS"][::std::mem::size_of::<_VCI_CAN_STATUS>() - 12usize];
    ["Alignment of _VCI_CAN_STATUS"][::std::mem::align_of::<_VCI_CAN_STATUS>() - 4usize];
    ["Offset of field: _VCI_CAN_STATUS::ErrInterrupt"]
        [::std::mem::offset_of!(_VCI_CAN_STATUS, ErrInterrupt) - 0usize];
    ["Offset of field: _VCI_CAN_STATUS::regMode"]
        [::std::mem::offset_of!(_VCI_CAN_STATUS, regMode) - 1usize];
    ["Offset of field: _VCI_CAN_STATUS::regStatus"]
        [::std::mem::offset_of!(_VCI_CAN_STATUS, regStatus) - 2usize];
    ["Offset of field: _VCI_CAN_STATUS::regALCapture"]
        [::std::mem::offset_of!(_VCI_CAN_STATUS, regALCapture) - 3usize];
    ["Offset of field: _VCI_CAN_STATUS::regECCapture"]
        [::std::mem::offset_of!(_VCI_CAN_STATUS, regECCapture) - 4usize];
    ["Offset of field: _VCI_CAN_STATUS::regEWLimit"]
        [::std::mem::offset_of!(_VCI_CAN_STATUS, regEWLimit) - 5usize];
    ["Offset of field: _VCI_CAN_STATUS::regRECounter"]
        [::std::mem::offset_of!(_VCI_CAN_STATUS, regRECounter) - 6usize];
    ["Offset of field: _VCI_CAN_STATUS::regTECounter"]
        [::std::mem::offset_of!(_VCI_CAN_STATUS, regTECounter) - 7usize];
    ["Offset of field: _VCI_CAN_STATUS::Reserved"]
        [::std::mem::offset_of!(_VCI_CAN_STATUS, Reserved) - 8usize];
};
pub type VCI_CAN_STATUS = _VCI_CAN_STATUS;
pub type PVCI_CAN_STATUS = *mut _VCI_CAN_STATUS;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _ERR_INFO {
    pub ErrCode: UINT,
    pub Passive_ErrData: [BYTE; 3usize],
    pub ArLost_ErrData: BYTE,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _ERR_INFO"][::std::mem::size_of::<_ERR_INFO>() - 8usize];
    ["Alignment of _ERR_INFO"][::std::mem::align_of::<_ERR_INFO>() - 4usize];
    ["Offset of field: _ERR_INFO::ErrCode"][::std::mem::offset_of!(_ERR_INFO, ErrCode) - 0usize];
    ["Offset of field: _ERR_INFO::Passive_ErrData"]
        [::std::mem::offset_of!(_ERR_INFO, Passive_ErrData) - 4usize];
    ["Offset of field: _ERR_INFO::ArLost_ErrData"]
        [::std::mem::offset_of!(_ERR_INFO, ArLost_ErrData) - 7usize];
};
pub type VCI_ERR_INFO = _ERR_INFO;
pub type PVCI_ERR_INFO = *mut _ERR_INFO;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _INIT_CONFIG {
    pub AccCode: DWORD,
    pub AccMask: DWORD,
    pub Reserved: DWORD,
    pub Filter: UCHAR,
    pub Timing0: UCHAR,
    pub Timing1: UCHAR,
    pub Mode: UCHAR,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _INIT_CONFIG"][::std::mem::size_of::<_INIT_CONFIG>() - 16usize];
    ["Alignment of _INIT_CONFIG"][::std::mem::align_of::<_INIT_CONFIG>() - 4usize];
    ["Offset of field: _INIT_CONFIG::AccCode"]
        [::std::mem::offset_of!(_INIT_CONFIG, AccCode) - 0usize];
    ["Offset of field: _INIT_CONFIG::AccMask"]
        [::std::mem::offset_of!(_INIT_CONFIG, AccMask) - 4usize];
    ["Offset of field: _INIT_CONFIG::Reserved"]
        [::std::mem::offset_of!(_INIT_CONFIG, Reserved) - 8usize];
    ["Offset of field: _INIT_CONFIG::Filter"]
        [::std::mem::offset_of!(_INIT_CONFIG, Filter) - 12usize];
    ["Offset of field: _INIT_CONFIG::Timing0"]
        [::std::mem::offset_of!(_INIT_CONFIG, Timing0) - 13usize];
    ["Offset of field: _INIT_CONFIG::Timing1"]
        [::std::mem::offset_of!(_INIT_CONFIG, Timing1) - 14usize];
    ["Offset of field: _INIT_CONFIG::Mode"][::std::mem::offset_of!(_INIT_CONFIG, Mode) - 15usize];
};
pub type VCI_INIT_CONFIG = _INIT_CONFIG;
pub type PVCI_INIT_CONFIG = *mut _INIT_CONFIG;
#[doc = " new add struct for filter /////////"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _VCI_FILTER_RECORD {
    pub ExtFrame: DWORD,
    pub Start: DWORD,
    pub End: DWORD,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of _VCI_FILTER_RECORD"][::std::mem::size_of::<_VCI_FILTER_RECORD>() - 12usize];
    ["Alignment of _VCI_FILTER_RECORD"][::std::mem::align_of::<_VCI_FILTER_RECORD>() - 4usize];
    ["Offset of field: _VCI_FILTER_RECORD::ExtFrame"]
        [::std::mem::offset_of!(_VCI_FILTER_RECORD, ExtFrame) - 0usize];
    ["Offset of field: _VCI_FILTER_RECORD::Start"]
        [::std::mem::offset_of!(_VCI_FILTER_RECORD, Start) - 4usize];
    ["Offset of field: _VCI_FILTER_RECORD::End"]
        [::std::mem::offset_of!(_VCI_FILTER_RECORD, End) - 8usize];
};
#[doc = " new add struct for filter /////////"]
pub type VCI_FILTER_RECORD = _VCI_FILTER_RECORD;
#[doc = " new add struct for filter /////////"]
pub type PVCI_FILTER_RECORD = *mut _VCI_FILTER_RECORD;
pub type DEVICE_HANDLE = *mut ::std::os::raw::c_void;
pub type CHANNEL_HANDLE = *mut ::std::os::raw::c_void;
unsafe extern "C" {
    pub fn ZCAN_OpenDevice(device_type: UINT, device_index: UINT, reserved: UINT) -> DEVICE_HANDLE;
}
unsafe extern "C" {
    pub fn ZCAN_CloseDevice(device_handle: DEVICE_HANDLE) -> UINT;
}
unsafe extern "C" {
    pub fn ZCAN_GetDeviceInf(device_handle: DEVICE_HANDLE, pInfo: *mut ZCAN_DEVICE_INFO) -> UINT;
}
unsafe extern "C" {
    pub fn ZCAN_IsDeviceOnLine(device_handle: DEVICE_HANDLE) -> UINT;
}
unsafe extern "C" {
    pub fn ZCAN_InitCAN(
        device_handle: DEVICE_HANDLE,
        can_index: UINT,
        pInitConfig: *mut ZCAN_CHANNEL_INIT_CONFIG,
    ) -> CHANNEL_HANDLE;
}
unsafe extern "C" {
    pub fn ZCAN_StartCAN(channel_handle: CHANNEL_HANDLE) -> UINT;
}
unsafe extern "C" {
    pub fn ZCAN_ResetCAN(channel_handle: CHANNEL_HANDLE) -> UINT;
}
unsafe extern "C" {
    pub fn ZCAN_ClearBuffer(channel_handle: CHANNEL_HANDLE) -> UINT;
}
unsafe extern "C" {
    pub fn ZCAN_GetReceiveNum(channel_handle: CHANNEL_HANDLE, type_: BYTE) -> UINT;
}
unsafe extern "C" {
    pub fn ZCAN_Transmit(
        channel_handle: CHANNEL_HANDLE,
        pTransmit: *mut ZCAN_Transmit_Data,
        len: UINT,
    ) -> UINT;
}
unsafe extern "C" {
    pub fn ZCAN_Receive(
        channel_handle: CHANNEL_HANDLE,
        pReceive: *mut ZCAN_Receive_Data,
        len: UINT,
        wait_time: ::std::os::raw::c_int,
    ) -> UINT;
}
unsafe extern "C" {
    pub fn ZCAN_TransmitFD(
        channel_handle: CHANNEL_HANDLE,
        pTransmit: *mut ZCAN_TransmitFD_Data,
        len: UINT,
    ) -> UINT;
}
unsafe extern "C" {
    pub fn ZCAN_ReceiveFD(
        channel_handle: CHANNEL_HANDLE,
        pReceive: *mut ZCAN_ReceiveFD_Data,
        len: UINT,
        wait_time: ::std::os::raw::c_int,
    ) -> UINT;
}
unsafe extern "C" {
    pub fn GetIProperty(device_handle: DEVICE_HANDLE) -> *mut IProperty;
}
unsafe extern "C" {
    pub fn ReleaseIProperty(pIProperty: *mut IProperty) -> UINT;
}
unsafe extern "C" {
    pub fn ZCAN_SetAbitBaud(device_handle: DEVICE_HANDLE, can_index: UINT, abitbaud: UINT) -> UINT;
}
unsafe extern "C" {
    pub fn ZCAN_SetDbitBaud(device_handle: DEVICE_HANDLE, can_index: UINT, dbitbaud: UINT) -> UINT;
}
unsafe extern "C" {
    pub fn ZCAN_SetCANFDStandard(
        device_handle: DEVICE_HANDLE,
        can_index: UINT,
        canfd_standard: UINT,
    ) -> UINT;
}
unsafe extern "C" {
    pub fn ZCAN_SetResistanceEnable(
        device_handle: DEVICE_HANDLE,
        can_index: UINT,
        enable: UINT,
    ) -> UINT;
}
unsafe extern "C" {
    pub fn ZCAN_SetBaudRateCustom(
        device_handle: DEVICE_HANDLE,
        can_index: UINT,
        RateCustom: *mut ::std::os::raw::c_char,
    ) -> UINT;
}
unsafe extern "C" {
    pub fn ZCAN_ClearFilter(channel_handle: CHANNEL_HANDLE) -> UINT;
}
unsafe extern "C" {
    pub fn ZCAN_AckFilter(channel_handle: CHANNEL_HANDLE) -> UINT;
}
unsafe extern "C" {
    pub fn ZCAN_SetFilterMode(channel_handle: CHANNEL_HANDLE, mode: UINT) -> UINT;
}
unsafe extern "C" {
    pub fn ZCAN_SetFilterStartID(channel_handle: CHANNEL_HANDLE, startID: UINT) -> UINT;
}
unsafe extern "C" {
    pub fn ZCAN_SetFilterEndID(channel_handle: CHANNEL_HANDLE, EndID: UINT) -> UINT;
}
unsafe extern "C" {
    pub fn VCI_OpenDevice(DeviceType: DWORD, DeviceInd: DWORD, Reserved: DWORD) -> DWORD;
}
unsafe extern "C" {
    pub fn VCI_CloseDevice(DeviceType: DWORD, DeviceInd: DWORD) -> DWORD;
}
unsafe extern "C" {
    pub fn VCI_InitCAN(
        DeviceType: DWORD,
        DeviceInd: DWORD,
        CANInd: DWORD,
        pInitConfig: PVCI_INIT_CONFIG,
    ) -> DWORD;
}
unsafe extern "C" {
    pub fn VCI_ReadBoardInfo(DeviceType: DWORD, DeviceInd: DWORD, pInfo: PVCI_BOARD_INFO) -> DWORD;
}
unsafe extern "C" {
    pub fn VCI_ReadErrInfo(
        DeviceType: DWORD,
        DeviceInd: DWORD,
        CANInd: DWORD,
        pErrInfo: PVCI_ERR_INFO,
    ) -> DWORD;
}
unsafe extern "C" {
    pub fn VCI_ReadCANStatus(
        DeviceType: DWORD,
        DeviceInd: DWORD,
        CANInd: DWORD,
        pCANStatus: PVCI_CAN_STATUS,
    ) -> DWORD;
}
unsafe extern "C" {
    pub fn VCI_GetReference(
        DeviceType: DWORD,
        DeviceInd: DWORD,
        CANInd: DWORD,
        RefType: DWORD,
        pData: PVOID,
    ) -> DWORD;
}
unsafe extern "C" {
    pub fn VCI_SetReference(
        DeviceType: DWORD,
        DeviceInd: DWORD,
        CANInd: DWORD,
        RefType: DWORD,
        pData: PVOID,
    ) -> DWORD;
}
unsafe extern "C" {
    pub fn VCI_GetReceiveNum(DeviceType: DWORD, DeviceInd: DWORD, CANInd: DWORD) -> ULONG;
}
unsafe extern "C" {
    pub fn VCI_ClearBuffer(DeviceType: DWORD, DeviceInd: DWORD, CANInd: DWORD) -> DWORD;
}
unsafe extern "C" {
    pub fn VCI_StartCAN(DeviceType: DWORD, DeviceInd: DWORD, CANInd: DWORD) -> DWORD;
}
unsafe extern "C" {
    pub fn VCI_ResetCAN(DeviceType: DWORD, DeviceInd: DWORD, CANInd: DWORD) -> DWORD;
}
unsafe extern "C" {
    pub fn VCI_Transmit(
        DeviceType: DWORD,
        DeviceInd: DWORD,
        CANInd: DWORD,
        pSend: PVCI_CAN_OBJ,
        Length: DWORD,
    ) -> ULONG;
}
unsafe extern "C" {
    pub fn VCI_Receive(
        DevType: DWORD,
        DevIndex: DWORD,
        CANIndex: DWORD,
        pReceive: PVCI_CAN_OBJ,
        Len: ULONG,
        WaitTime: INT,
    ) -> ULONG;
}
